import React, { Component } from 'react';

import Navbar from './Navbar';

import {
	Col,
	Row
} from 'antd';

class TermsOfUse extends Component {
	render() {
		const { userInfo } = this.props;
		return (
			<>
				<Navbar userInfo={userInfo} updateUserInfo={this.props.updateUserInfo} />
				<Row className="below-nav container" gutter={16}>
					<Col span={24}>
						<h2>Terms Of Use</h2>
						<p>These Advertising Terms and Conditions (the “Terms”) are entered into by and between Eduatlas.com, an SG EDUTECH brand, and the Client subscribing to Eduatlas services, and govern the terms of Client’s usage of Eduatlas services including but not limited to Listings and related information on Eduatlas’s websites; mobile applications; customer-care no. +918800889917, and other properties. The Terms are effective as of the date that you subscribe to the services, and that as the signer of this Agreement, you represent that you are authorized to sign on behalf of and bind the Client to the obligations under the Agreement. The Agreement (including its Purchase Order) becomes void if not accepted within the calendar month in which the Agreement was sent to Client by Eduatlas (“Agreement Expiration Date”).</p>
					</Col>
					<Col span={24}>
						<h3>I. Listing Account</h3>
						<p>Eduatlas will establish a Listing account enabling Client to purchase listing services (“Eduatlas listing”) that Eduatlas makes available to Client in connection with Eduatlas’s websites, mobile applications, and other properties, including properties set forth in a Purchase Order (“Services”). Each such purchase will be set forth in a purchase order agreed to in writing by both parties which sets forth the Eduatlas listings being purchased, applicable fees, the duration of the paid listing commitment (the “Commitment Period”), renewal terms, and the date that paid listing will commence, among other information (“Purchase Order”). Each Purchase Order is governed by and incorporated into the Terms, and any conflict between them will be resolved in favor of the Purchase Order. Client’s initial Purchase Order is attached to these Terms</p>
					</Col>
					<Col span={24}>
						<h3>II. Eduatlas Listing</h3>
						<p>Eduatlas Listing encompass a range of different advertising programs. The “Starter Kit” allows Client to access advanced features in connection with its business profile page, such as posting multiple programs, photo & video, and dedicated account support. As it develops new advertising features, Eduatlas may from time to time replace any of the foregoing features with features of substantially similar value.</p>
					</Col>
					<Col span={24}>
						<h3>III. Fees and Payment</h3>
						<p>Client will pay Eduatlas the fees specified in each Purchase Order for the duration of its term. The fees are fixed for the duration of the commitment period specified in the applicable Purchase Order, but may be modified by Eduatlas thereafter by providing one month’s prior written notice to Client. The fees are net of any taxes Client may be required to pay in its taxing jurisdiction. Payments are due in advance of the period for which they apply, or as otherwise set forth in the Purchase Order. Unpaid amounts or errors may be billed in subsequent invoices. If Client’s payment method fails or Client’s account is past due, Eduatlas may collect past due amounts using other collection mechanisms, and Client agrees to pay all expenses associated with such collection, including reasonable attorneys’ fees. Cancellation/Refund Policy: While availing any of the payment method/s available on the Website, Eduatlas will not be responsible or assume any liability whatsoever in respect of any loss or damage arising directly or indirectly to you. All payments made on the Website, including payments made toward registration for classes, are non-refundable. In the event payment is deducted from the User's account with non-completion of the booking, the exact amount shall be refunded to the User via the same mode of payment within 3-5 working days. All commercial terms are on a principal-to- principal basis between the Merchant and the users and Eduatlas’s payment facility is merely used to facilitate the completion of the transaction. Transaction charges, not limited to payment gateway charges, shall be applicable, unless explicitly waived off by Eduatlas. IF CLIENT PROVIDES EDUATLAS WITH CREDIT CARD, DEBIT CARD, OR BANK ACCOUNT INFORMATION, CLIENT AUTHORIZES EDUATLAS TO USE SUCH PAYMENT INFORMATION TO AUTOMATICALLY CHARGE CLIENT ON A RECURRING BASIS TO COLLECT ALL FEES DUE HEREUNDER. CLIENT REPRESENTS THAT HE OR SHE IS AUTHORIZED TO INCUR CHARGES AGAINST THE PAYMENT CARD USED TO PURCHASE EDUATLAS ADS. THE FORM OF PAYMENT CANNOT BE CHANGED OR ALTERED UNLESS ALL AMOUNTS DUE UNDER THE TERMS HAVE BEEN PAID IN FULL OR OTHERWISE AGREED TO BY THE PARTIES IN WRITING</p>
					</Col>
					<Col span={24}>
						<h3>IV. Representations and Warranties</h3>
						<p>Each party represents and warrants to the other that it is duly organized, validly existing, and in good standing under the laws of the jurisdiction in which it was organized; all contact and entity information is complete, correct and current, and the execution and delivery of the Terms, and the performance of the transactions contemplated hereby, are within its corporate powers, and have been duly authorized by all necessary corporate action. Client represents and warrants to Eduatlas that any information or materials that Client provides in connection with Eduatlas listings will (a) be true and complete, (b) not contain any material which violates Eduatlas’s content guidelines or which is otherwise unlawful, defamatory or obscene, or which infringes or violates any third-party rights (including any intellectual property rights or privacy or publicity rights) or which may encourage a criminal offense or otherwise give rise to civil liability and (c) comply with all applicable laws and regulations in its performance of the Terms (including all applicable privacy / data protection laws and regulations and laws related to Promotions). “Promotions” are any contest, sweepstakes, coupon or other promotion appearing on or promoted through the Site by Client. Eduatlas reserves the right to reject or remove any Advertising Materials at its sole discretion, and to alter any Advertising Materials to conform to technical specifications. Client further represents and warrants to Eduatlas that Client will not, and will not authorize or induce any other party, to: (a) generate automated, fraudulent or otherwise invalid inquiries, conversions or other actions; (b) use any automated means or form of scraping or data extraction to access, query or otherwise collect Eduatlas content and reviews from the Site, except as expressly permitted by Eduatlas or (c) use any Eduatlas trademarks in any manner without Eduatlas’s prior written consent. All rights not expressly granted to Client hereunder are reserved by Eduatlas.</p>
					</Col>
					<Col span={24}>
						<h3>V. Information About and Use of the Site</h3>
						<p>The Site allows consumers to post reviews about businesses like Client’s. The Site employs automated software to help it showcase the most relevant and reliable reviews while suppressing others. Client’s purchase of Eduatlas Ads will not influence the automated software, or otherwise allow or enable Client, directly or indirectly, to remove, alter or reorder the reviews on the Site.</p>
					</Col>
					<Col span={24}>
						<h3>VI. Termination</h3>
						<p>Each Purchase Order will expire at the end of the Commitment Period unless (i) otherwise terminated earlier under these Terms or (ii) the Purchase Order contains a renewal period that automatically extends the term of the Purchase Order beyond the Commitment Period (collectively the “PO Term”). Client must provide written notice (an email to Client’s assigned Eduatlas account representative is permissible) to terminate a Purchase Order on or before the 15th day of the month in order for the Purchase Order to terminate at the end of that month. If Client provides written notice after the 15th day of the month, then the Purchase Order will terminate at the end of the following month. Unless otherwise terminated as provided under the Terms, the Terms will automatically expire three (3) months after the termination or expiration of the last surviving Purchase Order. IF CLIENT TERMINATES A PURCHASE ORDER BEFORE THE END OF THE COMMITMENT PERIOD, CLIENT AGREES TO PAY ANY AND ALL EARLY TERMINATION FEES SET FORTH IN THE PURCHASE ORDER(S), RECOGNIZING THAT EDUATLAS BEARS CERTAIN UP-FRONT COSTS, AND THAT THERE IS AN IMPLIED PRICING DISCOUNT BASED ON THE LENGTH OF CLIENT’S CHOSEN COMMITMENT PERIOD. Eduatlas may terminate any Purchase Order or the Terms at any time for any or no reason without liability, effective immediately, by providing written notice to Client. In the event of such termination, Client will immediately pay all unpaid Eduatlas Ad fees through the date of termination, and Eduatlas will reimburse any fees that were prepaid for Eduatlas Ads to be rendered after the date of such termination.</p>
					</Col>
					<Col span={24}>
						<h3>VII. EDUATLAS’S DISCLAIMER OF WARRANTIES</h3>
						<p>CLIENT ACKNOWLEDGES AND AGREES THAT EDUATLAS SERVICES ARE PROVIDED TO CLIENT ON AN “AS IS”, “WITH ALL FAULTS” AND “AS AVAILABLE” BASIS. EDUATLAS MAKES NO WARRANTIES, EITHER EXPRESS OR IMPLIED, ABOUT THE EDUATLAS LISTING AND EXPRESSLY DISCLAIMS THE WARRANTY OF MERCHANTABILITY AND WARRANTY OF FITNESS FOR A PARTICULAR PURPOSE. FURTHERMORE, TO THE FULLEST EXTENT PERMITTED BY LAW, EDUATLAS SPECIFICALLY DISCLAIMS ALL WARRANTIES AND GUARANTEES REGARDING (I) THE PERFORMANCE, QUALITY AND RESULTS FOR THE SERVICE, (II) PAGE VIEWS, CONVERSIONS OR OTHER PERFORMANCE OR RESULTS FOR THE SERVICE, (III) THE ACCURACY OF THE INFORMATION THAT EDUATLAS PROVIDES IN CONNECTION WITH THE SITE OR EDUATLAS LISTING (E.G. REACH, SIZE OF AUDIENCE, DEMOGRAPHICS OR OTHER PURPORTED CHARACTERISTICS OF AUDIENCE), (IV) EDUATLAS’S ABILITY TO TARGET ADS TO OR IN CONNECTION WITH SPECIFIC USERS, TYPES OF USERS, USER QUERIES, OR OTHER USER BEHAVIORS. EDUATLAS SHALL NOT BE LIABLE FOR NON-PERFORMANCE DUE TO CAUSES BEYOND ITS REASONABLE CONTROL.</p>
					</Col>
					<Col span={24}>
						<h3>VIII. LIMITATIONS OF LIABILITY</h3>
						<p>FOR ALL CLAIMS ARISING FROM OR IN CONNECTION WITH A PURCHASE ORDER, EDUATLAS LISTING, OR THE TERMS THAT ARE NOT EXPRESSLY ADDRESSED IN THIS SECTION TITLED “LIMITATIONS OF LIABILITY”, EDUATLAS’S MAXIMUM LIABILITY AND CLIENT’S EXCLUSIVE REMEDY IS THE AGGREGATE FEES PAYABLE TO EDUATLAS HEREUNDER DURING THE SPECIFIED COMMITMENT PERIOD EXCEPT WHERE AND TO THE EXTENT PROHIBITED BY APPLICABLE LAW. NEITHER PARTY NOR ITS AFFILIATES WILL BE LIABLE FOR ANY INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL, OR EXEMPLARY DAMAGES (INCLUDING LOSS OF PROFITS OR REVENUE, OR INTERRUPTION OF BUSINESS) ARISING OUT OF OR RELATED TO A PURCHASE ORDER, THE EDUATLAS LISTING, THE SITE, OR THESE TERMS, REGARDLESS OF THE THEORY OF LIABILITY, EVEN IF A PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. Eduatlas does not represent in any manner that:  The information, data or contents of the Website are accurate;  The Website will be available at all times and will operate error free or that there will be uninterrupted access and service;  The integrity of the information on the Website or information you upload will be maintained;  We endorses any of the views of any of the users who may have posted content;  We have verified or guarantee the quality of services or representations made by any user of the Website;  We have verified the credit worthiness of any user;  We have screened or verified any of the information posted herein; and  The Website or any content is free from viruses or other malware. </p>
					</Col>
					<Col span={24}>
						<h3>IX. Indemnification</h3>
						<p>Client will indemnify, defend, and hold Eduatlas and its officers, directors, agents, and employees harmless from and against any and all claims, actions, losses, damages, liabilities, costs and expenses (including but not limited to attorneys’ fees and court costs) (collectively a “Third Party Claim”) arising out of or in connection with (i) the Advertising Materials, Client Instructions, or Client’s use of Eduatlas Ads, (ii) any breach of representations or warranties provided under these Terms by Client in Section IV, (iii) any Promotion, including any claims for any violation by the Promotion of any applicable law, rule or regulation, (iv) Client’s products or services or the provision thereof to end users. Eduatlas will notify Client promptly of any Third Party Claim for which it seeks indemnification and will permit Client to control the defense of such Third Party Claim with counsel chosen by Client; provided, that Client will not enter into any settlement that contains any admission of or stipulation to any guilt, fault, liability or wrongdoing on the part of Eduatlas without Eduatlas’s prior written consent.</p>
					</Col>
					<Col span={24}>
						<h3>X. Force Majeure</h3>
						<p>In no event shall Eduatlas be liable for any acts beyond our control or for any acts of god.</p>
					</Col>
					<Col span={24}>
						<h3>XI. Choice of Law and Arbitration</h3>
						<p>Any claim, controversy or dispute arising out of or relating to the Terms (“Claim”) shall be settled under the laws of Indian courts subject to laws of Republic of India. In the event of any dispute of whatever nature, such dispute shall be settled in good faith between the parties. In case, such dispute cannot be resolved by negotiation within 30 days, such dispute shall be referred to a binding arbitration in accordance with the provisions of the Arbitration and Conciliation Act 1996. The place of arbitration shall be Delhi, India. In case of the dispute requiring intervention of courts, courts in Delhi, India alone shall have exclusive jurisdiction.</p>
					</Col>
					<Col span={24}>
						<h3>XII.</h3>
						<p>In no event shall Eduatlas be liable for any loss of profits (anticipated or real), loss of business, loss of reputation, loss of data, loss of goodwill, any business interruption or any direct, indirect, special, incidental, consequential, punitive, tort or other damages, however caused, whether or not we have been advised of the possibility of such damages.</p>
					</Col>
					<Col span={24}>
						<h3>XIII. Miscellaneous</h3>
						<p>(a) The Terms and its exhibits are expressly limited to and made conditional upon Client’s acceptance of its terms and conditions before the Expiration Date. Any of Client’s terms or conditions which are in addition to or different from those contained in or added by way of interlineation to the Terms or any Purchase Order as originally provided to Client by Eduatlas which are not separately expressly agreed to in writing by both parties are deemed material and are hereby objected to and rejected by Eduatlas. No conditions, printed or otherwise, appearing on other contracts, orders or copy instructions which conflict with, vary, or add to these Terms will be binding on Eduatlas, and any conflicting or additional terms contain in any other documents or oral discussions are void. The Terms embody the entire and exclusive agreement between the parties respecting the subject matter of herein, and supersede any and all prior related oral, emailed or written representations and agreements between the parties. No statements or promises by either party have been relied upon in entering into these Terms, except as expressly set forth herein.
						(b) Anyone agreeing to the Terms on behalf of Client represents and warrants that it has full legal power and authority to enter into these Terms, perform its obligations hereunder, and authorize the fee payments set forth in the Purchase Order(s).
						(c) Notices under these Terms must be in writing and sent via facsimile, registered or certified mail or commercial courier to the parties at their respective addresses set forth herein.
					(d) The Terms may not be amended or modified except as agreed upon in writing by the parties. No provision in the Terms may be waived, except pursuant to a writing executed by the party against whom the waiver is sought to be enforced. Client may not assign any rights or obligations under the Terms without Eduatlas’s prior consent, and any purported assignment by Client shall be void. If any provision of the Terms is held to be invalid or unenforceable, the parties will substitute for the affected provision a valid or enforceable provision that approximates the intent and economic effect of the affected provision. Sections VII, VIII, IX, X and XI of the Terms will survive any termination of the Term.</p>
					</Col>
				</Row>
			</>
		);
	}
}

export default TermsOfUse;

